[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/blockassets/cgminer_client"

[[constraint]]
  branch = "master"
  name = "github.com/blockassets/prometheus_helper"
